# brew tap Homebrew/bundle

brew 'zsh'
brew 'git'
brew 'neovim'
brew 'rbenv'
brew 'pyenv'
brew 'clojure/tools/clojure'
brew 'zlib'
brew 'gauche'
brew 'go'
brew 'npm'
brew 'nkf'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'tmux'
brew 'jq'
brew 'git-secrets'
brew 'awscli'
brew 'hub'
brew 'gnupg'
brew 'pinentry-mac'
brew 'gnu-sed'
brew 'mkcert'
